kumuluzee:
  name: workout-service
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8081
    base-url: http://localhost:8081
  datasources:
    - jndi-name: jdbc/WorkoutServiceDS
      connection-url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/smartfitai_workouts
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:postgres}
      max-pool-size: 20

jwt:
  secret: Wq8U1MgZ9JTQUptfsNWtSuXxKen1Xqvl7TYQ1SwYou2pQnq/RtraU+Rn5OK+ZJVv
  expiration: 86400000
  issuer: smartfit-ai